module.exports = {
  classic: {
    black: "#1B1F00",
    white: "#f8f6f1",
    gray: ["#F3F0E8", "#EFEBE0", "#E7E1D0", "#444e00", "#2f3600", "#252a00"],
  },
  // https://hihayk.github.io/scale/#9/0/50/80/-51/67/20/14/f3f0e8/243/240/232/white
  light: {
    white: "#f8f6f1", // pen paper coffee background
    gray: [
      "#f3f0e8",
      "#e6e4db",
      "#d8d7ce",
      "#cbcbc1",
      "#bcbdb4",
      "#aeb0a7",
      "#a0a29a",
      "#92958d",
      "#848781",
      "#767a74",
    ],
  },
  dark: {},
  temp: {
    white: "TMP_WHITE",
    gray: [
      "TMP_GRAY_0",
      "TMP_GRAY_1",
      "TMP_GRAY_2",
      "TMP_GRAY_3",
      "TMP_GRAY_4",
      "TMP_GRAY_5",
      "TMP_GRAY_6",
      "TMP_GRAY_7",
      "TMP_GRAY_8",
      "TMP_GRAY_9",
    ],
    yellow: [
      "TMP_YELLOW_0",
      "TMP_YELLOW_1",
      "TMP_YELLOW_2",
      "TMP_YELLOW_3",
      "TMP_YELLOW_4",
      "TMP_YELLOW_5",
      "TMP_YELLOW_6",
      "TMP_YELLOW_7",
      "TMP_YELLOW_8",
      "TMP_YELLOW_9",
    ],
    pink: [
      "TMP_PINK_0",
      "TMP_PINK_1",
      "TMP_PINK_2",
      "TMP_PINK_3",
      "TMP_PINK_4",
      "TMP_PINK_5",
      "TMP_PINK_6",
      "TMP_PINK_7",
      "TMP_PINK_8",
      "TMP_PINK_9",
    ],
    green: [
      "TMP_GREEN_0",
      "TMP_GREEN_1",
      "TMP_GREEN_2",
      "TMP_GREEN_3",
      "TMP_GREEN_4",
      "TMP_GREEN_5",
      "TMP_GREEN_6",
      "TMP_GREEN_7",
      "TMP_GREEN_8",
      "TMP_GREEN_9",
    ],
    coral: [
      "TMP_CORAL_0",
      "TMP_CORAL_1",
      "TMP_CORAL_2",
      "TMP_CORAL_3",
      "TMP_CORAL_4",
      "TMP_CORAL_5",
      "TMP_CORAL_6",
      "TMP_CORAL_7",
      "TMP_CORAL_8",
      "TMP_CORAL_9",
    ],
    orange: [
      "TMP_ORANGE_0",
      "TMP_ORANGE_1",
      "TMP_ORANGE_2",
      "TMP_ORANGE_3",
      "TMP_ORANGE_4",
      "TMP_ORANGE_5",
      "TMP_ORANGE_6",
      "TMP_ORANGE_7",
      "TMP_ORANGE_8",
      "TMP_ORANGE_9",
    ],
    purple: [
      "TMP_PURPLE_0",
      "TMP_PURPLE_1",
      "TMP_PURPLE_2",
      "TMP_PURPLE_3",
      "TMP_PURPLE_4",
      "TMP_PURPLE_5",
      "TMP_PURPLE_6",
      "TMP_PURPLE_7",
      "TMP_PURPLE_8",
      "TMP_PURPLE_9",
    ],
    red: [
      "TMP_RED_0",
      "TMP_RED_1",
      "TMP_RED_2",
      "TMP_RED_3",
      "TMP_RED_4",
      "TMP_RED_5",
      "TMP_RED_6",
      "TMP_RED_7",
      "TMP_RED_8",
      "TMP_RED_9",
    ],
  },
};
